### ISSUE TITLE
how long does neuralangelo takes?

### ISSUE THREAD

**Issue by flow-specter** [mli0603/BlenderNeuralangelo#10]
hi, I wanna know that how long does neualangelo takes for a scene? maybe 12hours?

besides, how did you render the mesh with a given pose, blender?
![image](https://github.com/mli0603/BlenderNeuralangelo/assets/29993289/4d29cb72-3b16-49fb-a71d-e9df7791ff42)

**Comment by mli0603** [comment]
Hi @flow-specter 

The time depends on GPU. For my setup, it is around ~16 hours using our Python implementation.

The meshes are rendered with Blender.
