### ISSUE TITLE
Work with sparse reconstruction only

### ISSUE THREAD

**Issue by lxxue** [mli0603/BlenderNeuralangelo#12]
Thanks for the great work and open-sourcing this useful tool. 

It seems that the tool only needs sparse point clouds, camera poses, and images. The image distortion should be negligible for deciding bounding boxes. Therefore, I have the feeling that we do not need dense reconstruction which might take a long time to run. 

In that case, is it enough to just specify the image folder and the sparse folder for this addon?

**Comment by mli0603** [comment]
Hi @lxxue 

This addon only needs sparse reconstruction and image distortion. Dense reconstruction is not required :)
