### ISSUE TITLE
I got an error when load COLMAP Data too

### ISSUE THREAD

**Issue by ConquerorXv** [mli0603/BlenderNeuralangelo#13]
First, thanks for your work.

I add the BlenderNeuralangelo addon to Blender
I try to load toy_example, when I press the button load COLMAP Data, Python is reporting an error.

- I can see the pointcloud, but there is no image in image plane.

- And I can't switch camera views in the timeline, it seems that camera extrinsics is not loaded sucessfully

- In the folder 'toy_example/dense', there is blender_images, and I can see 17 images in it.

Python: Traceback (most recent call last): File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\neuralangelo_addon.py", line 1113, in execute load_camera(colmap_data, context) File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\neuralangelo_addon.py", line 963, in load_camera generate_camera_plane_texture(image_sequence) File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\neuralangelo_addon.py", line 891, in generate_camera_plane_texture material.node_tree.links.new(image_texture.outputs['Color'], principled_bsdf.inputs['Base Color']) AttributeError: 'NoneType' object has no attribute 'inputs'
![1](https://github.com/mli0603/BlenderNeuralangelo/assets/130122802/35e0b665-9782-49a7-8dae-89a554ca617f)

**Comment by mli0603** [comment]
Hi @ConquerorXv 

Thank you for reporting this. The log above suggests that the node creation step failed, and thus the rest of the loading steps. I wonder if this is something related to 3.6 (I've been testing with 3.4). Let me bump up the version on my end to test.

**Comment by mli0603** [comment]
Hi @ConquerorXv 

I did a fresh installation of Blender 3.6 and it worked out of the box. I wonder if this has something to do with Chinese characters in the file path. Is this the case?
![image](https://github.com/mli0603/BlenderNeuralangelo/assets/13513172/180fdf47-0a72-4292-b8c7-e1724b83316c)

**Comment by ConquerorXv** [comment]
Thank you very much @mli0603 , it's a language issue, I set Blender's language to English and it works perfectly!
