### ISSUE TITLE
Bounding Box is Massive and Cant be Scaled down Enough

### ISSUE THREAD

**Issue by ceeparsons** [mli0603/BlenderNeuralangelo#17]
Hey there, thanks for creating this tool, it's been a really exciting one to start working with.

I've been trying to create a tight bounding box for a head but I'm having problems making it happen. After running the COLMAP but before generating the JSON file for data loading, I loaded up my COLMAP data in blender and the bounding box seemed reasonably well sized (as seen in the photo below).

![Screenshot 2023-09-21 104142](https://github.com/mli0603/BlenderNeuralangelo/assets/145613370/d9ddaaa3-7706-4ffa-90a2-9d5b4cb87c64)

The moment I try to change it's size though it becomes massive and no matter how much I scale it down it's still way too big for my model.

![Screenshot 2023-09-21 104216](https://github.com/mli0603/BlenderNeuralangelo/assets/145613370/9c1edeff-9bf4-4888-863a-2bc3f5e0ddf8)

I've also noticed a few of my point clouds are very unaligned with my camera, I've included those below for reference. Please let me know if this is a glitch or if there may be a way to make this work!

![Screenshot 2023-09-21 104038](https://github.com/mli0603/BlenderNeuralangelo/assets/145613370/4b98af8b-7b95-4a98-89af-055b4893d70c)
![Screenshot 2023-09-21 104058](https://github.com/mli0603/BlenderNeuralangelo/assets/145613370/65b07108-83d1-45cc-88ee-2439aa187f8f)
![Screenshot 2023-09-21 104108](https://github.com/mli0603/BlenderNeuralangelo/assets/145613370/15f28ab1-5b98-4e7c-a857-cb160cea3abc)

Thanks :)

**Comment by mli0603** [comment]
Hi @ceeparsons 

For the offset issue, I want to check with you if you enabled single camera COLMAP by using `--ImageReader.single_camera=true`. This is the only case that I can think of where you will have an offset.

I have not encountered the zoom-in error you mentioned. I think this may be a bug in the code. Can you try making the `50` value a larger one (such as 100) in this line and see if it fixes it?
https://github.com/mli0603/BlenderNeuralangelo/blob/3d87fb75d6f4a73dcd9a6ba49386922fa048f100/neuralangelo_addon.py#L1009

**Comment by ceeparsons** [comment]
I never specifically enabled it, but upon checking my run_colmap.sh file I found that it was indeed already enabled. 

`colmap feature_extractor
![Screenshot 2023-09-22 090549](https://github.com/mli0603/BlenderNeuralangelo/assets/145613370/831c61d8-afde-4af7-82df-4d6ce9c95d37)
  --image_path=${1}/images_raw \
  --ImageReader.camera_model=SIMPLE_RADIAL  \
  --ImageReader.single_camera=true \`

After that, I tried making `max=100`, and still had the same problem, before making it `max=150`, which seemed to fix it! It looks like the smaller bounding box it was trying to start with had values above 50 in almost all directions.

![Screenshot 2023-09-22 090220](https://github.com/mli0603/BlenderNeuralangelo/assets/145613370/b565ef49-b0a0-4de4-bbf3-ce02654f22a1)

After having these larger values I was able to properly scale the bounding box! Thanks :)

![Screenshot 2023-09-22 090549](https://github.com/mli0603/BlenderNeuralangelo/assets/145613370/cbd3da04-9a54-4364-a4cb-de15c73337a1)
