### ISSUE TITLE
I got an error when load COLMAP Data

### ISSUE THREAD

**Issue by julianzhao88** [mli0603/BlenderNeuralangelo#6]
when I load COLMAP Data,there is an error
Python: Traceback (most recent call last):File"neuralangelo addon.py", line 1095, in executeload camera(colmap data, context)File "neuralangelo addon.py", line 969 , in load camneragenerate camera plane texturelimage sequence)File "neuralangelo addon.py, line 897 , in generate camera plane texturematerial.node tree.links.new(image texture.outputs[ 'Color' ], principled bsdf inputs[Base Color'])AttributeError: 'NoneType' object has no attribute 'inputs'
the version of  blender is 3.5.1

**Comment by mli0603** [comment]
Hi @julianzhao88 

Thank you for your interest in our work.

This error is coming from loading images as textures, where the path is defined here

https://github.com/mli0603/BlenderNeuralangelo/blob/bbeb0b114e22d8778668b2a4ada9307db6a23e32/neuralangelo_addon.py#L936

If you have followed the commands from COLMAP exactly, you should expect a folder structure [like the following]:(https://github.com/mli0603/BlenderNeuralangelo/tree/main#0-running-colmap)

```
|__ dense (or your customized work directory)
    |__ images (folder of undistorted images)
    |__ sparse (folder of sparse reconstruction results)
    |__ run-colmap-geometric.sh
    |__ run-colmap-photometric.sh
```

Most likely your folder structure is different from what colmap is expecting.

**Comment by crazySyaoran** [comment]
same error here... the folder structure is:
```
|__ dense (or your customized work directory)
    |__ images (folder of undistorted images)
    |__ sparse (folder of sparse reconstruction results)
    |__ run-colmap-geometric.sh
    |__ run-colmap-photometric.sh
```

**Comment by mli0603** [comment]
Hi @crazySyaoran 

Thanks for the update. Would you mind sharing your colmap results with me (I.e., the ‘dense’ folder) so I can replicate your issue?

**Comment by crazySyaoran** [comment]
Thanks for reply. I just used the toy_example in your code.

**Comment by crazySyaoran** [comment]
I updated my blender to latest version 3.5 and error message gone. Thank you.

**Comment by julianzhao88** [comment]
> I updated my blender to latest version 3.5 and use English as language then the error message gone. Thank you.

yes，use English,it works.
Thanks

**Comment by simonzhou06** [comment]
I am having the same error even when I load the example dense folder.
