### ISSUE TITLE
Would you open source the code of Neuralangelo?

### ISSUE THREAD

**Issue by Liu-SD** [mli0603/BlenderNeuralangelo#7]

**Comment by flow-specter** [comment]
We are looking forward！

**Comment by voldemortX** [comment]
It would be a great contribution to the community. Looking forward to it. Are there plans to open-source all/part of the code? @mli0603

**Comment by Ivan29B** [comment]
The technology is amazing, and in many ways surpasses classical photogrammetry. I really want to feel, waiting ...)
