### ISSUE TITLE
I got an error when load COLMAP Data

### ISSUE THREAD

**Issue by simonzhou06** [mli0603/BlenderNeuralangelo#9]
When I try to load the example one the error was: 

Python: Traceback (most recent call last):
  File "\neuralangelo_addon.py", line 1095, in execute
    load_camera(colmap_data, context)
  File "\neuralangelo_addon.py", line 950, in load_camera
    bpy.ops.image.open(filepath=blender_img_path, directory=blender_img_path, files=blender_file_names_formatted,
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.5.1.0_x64__ppwjx1n5r4v9t\Blender\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties:  IMAGE_OT_open.files error converting a member of a collection from a dicts into an RNA collection, failed with: TypeError: Converting a Python list to an RNA collection: keyword "type" missing

**Comment by simonzhou06** [comment]
Sure, I installed the git respiratory to my desktop and I ran the code in the blender with version 3.5.1 and my project folder is on the desktop, and yes I see the blender_images inside the dense folder.

**Comment by mli0603** [comment]
Please see issue https://github.com/mli0603/BlenderNeuralangelo/issues/13
